### ISSUE TITLE
Can't run flatpak as a native wayland app

### ISSUE THREAD

**Issue by matosjoaops** [flathub/com.logseq.Logseq#10]
When running the flatpak as a native wayland app using the following command:

`flatpak run com.logseq.Logseq --enable-features=UseOzonePlatform --ozone-platform=wayland`

The app doesn't start and I get the following error message:

```
LaunchProcess: failed to execvp:
xdg-settings
[3:0818/002507.566126:ERROR:wayland_connection.cc(209)] Failed to connect to Wayland display
[3:0818/002507.566135:ERROR:ozone_platform_wayland.cc(226)] Failed to initialize Wayland platform
[3:0818/002507.566140:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
/app/bin/run.sh: line 2:     3 Segmentation fault  (core dumped) zypak-wrapper.sh /app/logseq/Logseq "$@"
```

When running the AppImage with the same arguments this issue isn't present.

This problem was also mentioned in the comments of [this issue](https://github.com/logseq/logseq/issues/5642) but it seems to be unrelated.

**Comment by kanru** [comment]
Hi, the latest version should have better wayland support.

Try this

```
flatpak run --socket=wayland com.logseq.Logseq --ozone-platform-hint=auto \
    --enable-features=WaylandWindowDecorations
```

**Comment by hreynier** [comment]
@kanru thanks, can confirm this works after updating. When I run this command I still get some launch process related errors but doesn't seem to impact the app.

```
LaunchProcess: failed to execvp:
xdg-settings
[3:0902/120015.235528:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket
/run/dbus/system_bus_socket: No such file or directory
```

**Comment by matosjoaops** [comment]
@kanru The command you provided also works for me. Thank you!
