### ISSUE TITLE
Flathub release not reflecting latest release

### ISSUE THREAD

**Issue by Bandageboyz** [flathub/com.logseq.Logseq#108]
The flathub version of logseq is loading version 9.17 but the release information in the Flathub repository is showing it should be 09.20. This is the install screenshot.
![Screenshot 2023-11-23 22 13 42](https://github.com/flathub/com.logseq.Logseq/assets/151882569/c58e20a6-65d4-4c37-a133-d11bafe65297)

**Comment by mmazur** [comment]
You sure you don't have two copies installed? You can run this to verify:

```
flatpak list|grep logseq
```

**Comment by Bandageboyz** [comment]
Thanks. No I only have the one installation.
