### ISSUE TITLE
runtime-version 22.08 breaks cursor theme and size on wayland.

### ISSUE THREAD

**Issue by queeup** [flathub/com.logseq.Logseq#11]
`--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` option used for fractional scaling blurry font problem fix.

https://user-images.githubusercontent.com/87835/190284208-d3d85f6d-40c6-46b3-b111-38e36d88a725.mp4

**Comment by kanru** [comment]
@queeup thanks for the report. Looks like upstream has already took action. I the meantime I'll revert the runtime version.

**Comment by kanru** [comment]
Upstream issue https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1484
