### ISSUE TITLE
Missing `ssh-askpass`?

### ISSUE THREAD

**Issue by giladwo** [flathub/com.logseq.Logseq#35]
Hi,

`git {fetch,push}` fails with the following error:
![image](https://user-images.githubusercontent.com/25708271/208157505-e3457984-6a04-420c-8254-59ef7ab18a41.png)

I don't know much about Flatpak, but considering the fact `com.vscodium.vscodium` etc have no issue using git, I tried poking around with `flatpak run --command=sh com.logseq.Logseq` and found out `com.logseq.Logseq` doesn't even have `git` in the runtime path? I'm probably missing something, because git operations that do not require ssh keys work as intended.

Anyhow, both `vscodium` and `logseq` appear to be using the same runtime (Freedesktop Platform 22.08.4), so I guess some extension can be copied over here to solve this?

PS: Thanks for maintaining this, I hope upstream would consider using Flatpak as well officially.

**Comment by kanru** [comment]
Logseq bundles a git library https://github.com/desktop/dugite and that bundles its git executable.

You can find it at this path

```sh
ls $(flatpak info -l com.logseq.Logseq)/files/logseq/resources/app/node_modules/dugite/git
``` 

Or using flatpak

```sh
flatpak run --command=/app/logseq/resources/app/node_modules/dugite/git/bin/git com.logseq.Logseq
```

Were you trying to clone a git repository with ssh? I haven't tried it before, but I guess it will also need ssh to be available in the runtime path.

**Comment by giladwo** [comment]
> Logseq bundles a git library https://github.com/desktop/dugite and that bundles its git executable.

Cool, thanks for the clarification.

> Were you trying to clone a git repository with ssh?

No, I was just trying to sync (fetch, pull, push) with a remote, i.e.
![image](https://user-images.githubusercontent.com/25708271/208661634-d6c9c116-a3ff-452f-95ea-3e2c41bd9c18.png)

Just out of curiosity, trying to clone raises a different error (from inside `flatpak run --command=sh com.logseq.Logseq`):
```
$ /app/logseq/resources/app/node_modules/dugite/git/bin/git clone git@github.com:giladwo/giladwo
Cloning into 'giladwo'...
warning: templates not found in //share/git-core/templates
Enter passphrase for key ...:
error: cannot run index-pack: No such file or directory
fatal: fetch-pack: unable to fork off index-pack
remote: Enumerating objects: 12, done.
```
(Tested with both github and sourcehut, just to be sure it's not somehow unique to srht).

**Comment by giladwo** [comment]
Hi,
Any ideas what can be done about this?
I'd really like to be able to `git pull` etc. from within Logseq.

**Comment by sebastian-de** [comment]
I can use git from within the flatpak without problems. I just had to grant access to my SSH agent:
```
flatpak -u override --socket=ssh-auth com.logseq.Logseq
```

I use the following Logseq plugin to push/pull: https://github.com/haydenull/logseq-plugin-git

**Comment by sebastian-de** [comment]
Yes, I guess it makes sense to add this to `finish-args`.
The Obsidian flatpak apparently does this as well: https://github.com/flathub/md.obsidian.Obsidian/blob/f4dff22a22551bad36aed2edc0246f0c050ff6a8/md.obsidian.Obsidian.yml#L19

**Comment by giladwo** [comment]
@sebastian-de Yes, it fixes the issue!
Thanks!

**Comment by kanru** [comment]
Please help me test the build from https://github.com/flathub/com.logseq.Logseq/pull/115#issuecomment-1846255369

Thanks 😊
