### ISSUE TITLE
Errors when trying to build a flatpak for 0.6.1

### ISSUE THREAD

**Issue by alexdesiqueira** [flathub/com.logseq.Logseq#5]
Hey @kanru,
I tried to build a flatpak for 0.6.1 according to the instructions in `README`. The process goes fine until the last step, `flatpak-builder`:

```bash
$ flatpak-builder --user --install --force-clean build-dir/ com.logseq.Logseq.json
(...)
Running: yarn
yarn install v1.22.17
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
[1/4] Resolving packages...
error Couldn't find package "react-icon-base@2.1.0" required by "react-icons@2.2.7" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: module logseq: Child process exited with code 1
```

Never worked with `yarn` nor `npm`. I tried installing the mentioned packages with `npm`, but someone said to not mix `yarn` and `npm`, then I restarted the process. Twice. :joy: 
Any ideas on how I could debug that?
Thanks!

**Comment by kanru** [comment]
Hey @alexdesiqueira 

I also just noticed 0.6.1 was released last week so I was also taking a look this earlier today. Normally the steps in the README would work, but the `yarn.lock` file in the 0.6.1 release is missing the dependency `react-icon-base@2.1.0` so a patch is needed to fix the `yarn.lock` file.

```patch
--- logseq-0.6.1.orig/yarn.lock
+++ logseq-0.6.1/yarn.lock
@@ -6760,6 +6760,11 @@ react-grid-layout@0.16.6:
     react-draggable "3.x"
     react-resizable "1.x"
 
+react-icon-base@2.1.0:
+  version "2.1.0"
+  resolved "https://registry.yarnpkg.com/react-icon-base/-/react-icon-base-2.1.0.tgz#a196e33fdf1e7aaa1fda3aefbb68bdad9e82a79d"
+  integrity sha1-oZbjP98eeqof2jrvu2i9rZ6Cp50=
+
 react-icons@2.2.7:
   version "2.2.7"
   resolved "https://registry.yarnpkg.com/react-icons/-/react-icons-2.2.7.tgz#d7860826b258557510dac10680abea5ca23cf650"
```

I'm currently trying to fix another missing dependency `electron-dl` for offline build. If I can fix it then I'll be able to publish a new version to Flathub today :)

**Comment by kanru** [comment]
You can try this commit https://github.com/flathub/com.logseq.Logseq/commit/073c644efd5a5cbcfaa6a58d8426bd01adb709db

**Comment by alexdesiqueira** [comment]
Ooh, thanks for that. Yeah, the idea was to push a new version and take the burden out of ya for this one :)

**Comment by alexdesiqueira** [comment]
Gonna close this one. Let's wait for you, then, and check how you solve these; maybe I can help you better in the future.
Thanks again!
